{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gearworks-mc.fullname" . }}-redis
  labels:
    {{- include "gearworks-mc.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.cluster.redis.port }}
      targetPort: {{ .Values.cluster.redis.port }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
